DROP SERVICES IF EXISTS;
CREATE DATABASE SERVICES;
USE SERVICE;

CREATE TABLE USER(
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    user_password  VARCHAR(255) NOT NULL,
)